io/encryption.go
io/socks/socks.go
io/vmess/vmess.go
net/freedom/freedom.go
net/socks/socks.go
net/vmess/vmessin.go
net/vmess/vmessout.go

Use &struct{} instead of new, more generic way to new one

Use &struct{} instead of new

---

spec/guide.md

Revert "Update guide.md"

---

contrib/docker/Dockerfile
contrib/docker/README.md
contrib/docker/build.sh
contrib/docker/gen-server-cfg.sh
contrib/docker/run.sh
release/install.sh

It's easier for people to setup their own v2ray service with docker.

docker build for v2ray

---

transport/internet/dialer.go
transport/internet/dialerSubstitute.go

加入了用于支持libv2ray的相关接口，这些接口是实现V2RayGo的VPNService的功能所必须的。
不建议修改新加入的接口，因为其已经在libv2ray中使用。

Solve #218: Supporting substitute of the default Dialer.

---

transport/internet/udp/dispatcher.go

Fix typo, fix #715

---

app/dispatcher/default.go
app/dispatcher/sniffer.go

Fix sniff typo

---

proxy/vmess/vmess.go

Remove duplicate len function call.

Remove duplicate len function call.

---

app/router/config.go

From effective Go: https://golang.org/doc/effective_go.html#switch
> It's therefore possible—and idiomatic—to write an if-else-if-else chain as a switch.

app/router: rewrite if-else chain to switch

---

.gitmodules
testing/scenarios/socks_test.go

Use h12.io/socks instead of vendored old one

---

go.mod
go.sum

Signed-off-by: kuoruan <kuoruan@gmail.com>

Fix go modules

---

infra/conf/router.go

Signed-off-by: heapops <heapbin1@gmail.com>

Fix ip rule with custom geoip file

---

infra/bazel/zip.bzl
transport/internet/http/hub.go

I am not an expert of bazel, just managed to make it work again. #1756

fix incompatible errors when building with bazel 0.26+

---

proxy/shadowsocks/server.go

fix a crash problem of fetching user from a nil request which returned by shadowsocks failed to read IV

fix a crash problem

---

transport/internet/tls/config_windows.go

Revert "Fix self-signed certificates on Windows"

---

infra/conf/dns.go

Allow dns hosts object to read domains from external file.

Support external domain file for dns hosts

---

app/dns/dnscommon.go
app/dns/dnscommon_test.go
app/dns/dohdns.go
app/dns/nameserver.go
app/dns/server.go
app/dns/udpns.go
app/proxyman/outbound/handler.go
common/mux/client.go
common/session/context.go
infra/conf/dns.go
infra/conf/v2ray.go
infra/conf/v2ray_test.go

* introduce support for DNS OVER HTTPS (RFC 8484)
* refactored DNS module
* all config changes are compatible with formal format, no breaking changes.

DOH client supported

---

app/dns/dnscommon.go
app/dns/server.go

See https://github.com/v2ray/v2ray-core/issues/1565

revert broken dns changes

---

common/platform/ctlcmd/ctlcmd.go
common/platform/platform.go
infra/conf/v2ray.go
infra/control/command.go
infra/control/config.go
main/main.go

Revert "add arg -confdir"

---

release/release-ci.sh

Update rules dat file URL to GitHub default latest downloadable assets URL

Update rules dat file URL

---

proxy/http/server.go
proxy/socks/protocol.go
proxy/socks/server.go

Pass username to inbound.User.Email in http/socks server.

Support user routing and stats in http/socks inbound server

---

release/install-release.sh

feat: Install directly from zip file

---

transport/internet/sockopt_linux.go

As a follow-up to
https://github.com/v2ray/v2ray-core/pull/1940#issuecomment-549821507
@eycorsican
This is another fix to https://github.com/v2ray/v2ray-core/issues/1881

Add SO_REUSEPORT to inbound

---

release/config/systemd/v2ray.service

之前我把第八行的注释给写反了，要纠正一下
并且在 Documentation 加了白话文的链接

Fixed minor bugs & add Documentation

---

release/release-ci.sh

due to https://github.com/v2ray/geoip/issues/18

Update dat files download links

---

app/reverse/bridge.go
proxy/http/client.go

Revert "Reduce http proxy client overhead by 1RTT"

---

azure-pipelines.template.yml
azure-pipelines.yml

Update Golang version

---

SECURITY.md

See https://github.com/v2ray/discussion/issues/726 for reasonings.

Discourage reporting security vulnerabilities publicly

---

.github/workflows/test.yml
app/stats/stats.go
features/stats/stats.go
go.mod
go.sum

due to https://github.com/v2fly/v2ray-core/pull/171

Merge v2fly
