v2ray/v2ray-core

id.go
io/socks/socks.go
net/address.go
net/socks/socks.go
net/vmess/config.go
ray.go

* Add more error check.
* Declare the field name in composite literal.

Add more error check and declare the field name in composite literal.

---

proxy/http/http.go
proxy/http/http_test.go

This patch defers Conn.Close call until all responses from server
has been written to the client. It should fix many of the hanging
issues we have with plain HTTP requests.

http bug fixes & disable keep-alive

---

tools/docker/Dockerfile
tools/docker/README.md
tools/docker/build.sh
tools/docker/docker-entrypoint.sh
tools/docker/gen-server-cfg.sh

Generate server config on first run, so it's possible to build an image for everyone to use.

generate server config on first run

---

release/install-release.sh

Hint downloading address before installing, in case the download is blocked and the user may manually overwrite the installation process. (Otherwise, the "downloading" hint will never appear when download is blocked.)

Update install process: hint before downloading

---

proxy/internal/handler_cache.go

Fixed: internal.CreateOutboundHandler should return ErrorProxyNotFound if !found instead of ErrorNameExists.
No expected compatibility damage.
This is a fix for a non-critical bug. No more explanation is necessary.

Fixed: internal.CreateOutboundHandler should return ErrorProxyNotFound if !found instead of ErrorNameExists

---

proxy/proxy.go
proxy/vmess/inbound/inbound.go
proxy/vmess/outbound/outbound.go
transport/config.go
transport/config_json.go
transport/hub/dialer.go
transport/hub/kcp.go
transport/hub/kcp/config.go
transport/hub/kcp_test.go
transport/hub/kcpv/config.go
transport/hub/kcpv/config_json.go
transport/hub/kcpv/crypto.go
transport/hub/tcp.go
transport/transport.go

TCP连接在高延迟，高带宽，较高丢包环境下，不能有效利用带宽。目前TCP连接下的VMess协议在这种网络环境下速度缓慢，甚至出现连接超时错误。
KCP可以更加有效的利用带宽降低延迟，很大程度上减少因为恶劣的网络环境导致的连接不稳。
通过提高代理连接的速度，可以有效的改善使用v2ray的体验。
新增加了一部分API，请查看 #162 了解详情。 
需要注意的是：引入了 github.com/xtaci/kcp-go 库， 这个库的API的稳定性值得怀疑，在合并时可以考虑将该库的地址替换为V2ray可以有效控制的地址。

Add KCP(UDPSession) as a transport for v2ray, reslove #162

---

proxy/http/server.go

According to [RFC 2616](https://tools.ietf.org/html/rfc2616#section-2.2)
```plain
HTTP/1.1 defines the sequence CR LF as the end-of-line marker for all
protocol elements except the entity-body (see appendix 19.3 for
tolerant applications).
```

fix HTTP proxy OK response

---

common/signal/timer.go

The following code leads to timer leak. `defer ticker.Stop()` cannot stop the new ticker because of different addresses. The patch fixes this bug.
```
case timeout := <-t.timeout:
ticker.Stop()
ticker = time.NewTicker(timeout)
```

fix timer leak

---

proxy/http/server.go
proxy/http/server_test.go

Go automatically sets HTTP header `User-Agent` to `Go-http-client/1.1` if it hasn't been set before, which in some cases breaks the transparency of proxy.
Such behavior can be prevented by setting it to an empty string.

Prevent UA from being set to golang's default ones

---

release/install-release.sh

```
➜  a git:(master) ✗ ERROR=`cp c d`
cp: c: No such file or directory
➜  a git:(master) ✗ echo $?
1
➜  a git:(master) ✗ echo $ERROR
➜  a git:(master) ✗ ERROR=`cp c d 2>&1`
➜  a git:(master) ✗ echo $?
1
➜  a git:(master) ✗ echo $ERROR
cp: c: No such file or directory
```
According above test suggests ERROR is always EMPTY string if we don't capture command error output

Capture command error output

---

app/dns/server.go

This function has never been called.

Clean useless code

---

common/protocol/server_spec.go

在前面的方法中, 都使用了 s 作为变量,  这里虽然实现了  ValidateStrategy interface,  从代码的一致性上看还是 继续用  s  比较合理.

consistent  ServerSpec  variable name

---

release/install-release.sh

现在的版本号，如果是Pre-release的话，都会在主版本号后再加一个小版本号。但是在检查更新时，所有的Pre-release版本都会被认为不是最新的版本，导致更新回最新的大版本。
这个改动就截取当前运行版本的版本号前2个位置，所以只要运行的Pre-release版本是最新大版本系列下的，就能通过最新版本的检测。
由于Pre-release一般存在时间也不会太长，这个改动有没有必要，还请作者来定夺。

install-release.sh检查更新时忽略小版本号

---

proxy/dokodemo/dokodemo.go
transport/internet/sockopt_linux.go

Related: #1432 
Currently Dokodemo TPROXY mode has following issues when handling UDP traffic:
1. A new socket is created inside Dokodemo to send data back to client, this socket is bound to exact address pair of the connection. Due to inner workings of TPROXY, all packets sent from client will be intercepted by this socket and get lost.
2. Because all data is redirected to the new socket, `udpWorker` won't get any data to trigger timer update, all UDP connections will be GCed after some time regardless of whether there is any traffic.
3. If `freedom` is used as outbound, SO_MARK is not applied to the packets which causes routing loop.
This pull request fixes 1 and 3. Issue 2 requires quite a few changes to the architecture and I am not sure what is the best way to fix it, would be great …

Fix UDP issue in Dokodemo TPROXY mode

---

infra/conf/log.go

access and error logger can be muted by setting each value to `none`.
Useful if user prefer stdout logger with either access or error, but not both.

add: mute access/error logger seperately

---

app/dns/server.go
app/proxyman/inbound/inbound.go
app/proxyman/outbound/outbound.go
app/reverse/bridge.go
app/reverse/portal.go
app/router/balancing.go
common/protocol/http/headers.go
common/protocol/http/sniff.go
common/protocol/tls/sniff.go
common/strmatcher/domain_matcher.go
infra/conf/api.go
infra/conf/router.go
infra/conf/shadowsocks.go
infra/conf/transport_internet.go
infra/control/cert.go
infra/control/command.go
infra/control/verify.go
proxy/http/server.go
proxy/vmess/inbound/inbound.go
proxy/vmess/validator.go
transport/internet/domainsocket/config.go
transport/internet/headers/http/config.go
transport/internet/http/config.go
transport/internet/tls/config.go
transport/internet/tls/tls.go
transport/internet/websocket/config.go

* Rewrite empty string checks more idiomatically.
* Change strings.ToLower comparisons to strings.EqualFold.
* Rewrite switch statement with only one case as if.

Some code improvements

---

transport/internet/http/hub.go

When v2ray (using h2 transport) and the reverse proxy are on the same machine, maybe there is no need to use TLS between v2ray and the reverse proxy. #1644

add server side h2c support

---

common/log/access.go
common/mux/server.go
proxy/shadowsocks/server.go
proxy/vmess/inbound/inbound.go

给 shadowsocks 和 vmess 的 access log 里添加了 email 字段，效果如下，如果没有设置 email，则不会显示。
mux模式暂时也无法显示。

Add email into access log for shadowsocks and vmess

---

proxy/http/client.go

http client file from PR #1813 is missing !confonly tag,  cause build error on `v2ctl` with -tags confonly

fix: !confonly missing in http client

---

proxy/http/client.go

There is no newline separating the build tag and the package declaration in proxy/http/client.go

blank row between build and package

---

app/proxyman/outbound/outbound.go

复现配置文件，只要包含 `api` 就会有问题。
```json
{
"api": {
"tag": "api",
"services": [
"HandlerService",
"LoggerService",
"StatsService"
]
}
}
```
```
$  docker-compose up
Creating network "v2ray-controller_default" with the default driver
Creating v2ray ... done
Attaching to v2ray
v2ray    | V2Ray 4.19.1 (Let's Fly) Custom
v2ray    | A unified platform for anti-censorship.
v2ray    | panic: runtime error: invalid memory address or nil pointer dereference
v2ray    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x800900]
v2ray    |
v2ray    | goroutine 1 [running]:
v2ray    | v2ray.com/core/app/proxyman/outbound.(*Manager).RemoveHandler(0xc0000aafa0, 0xd99b40, 0xc000036018, 0xc000036a40, 0x3, 0x0, 0x0)
v2ray    | 	v2ray.com/core/app/proxyman/outbound/outbound.go:133 +0xb0
v2ray    | …
```

fix segment fault when use api remote config

---

proxy/vmess/encoding/client.go

Currently core shows transport error at `[Info]` level:
```
2019/08/27 08:51:57 [Info] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:v1.mux.cool:9527 via tcp:nov.meponse header > x509: certificate signed by unknown authority   
```
```
2019/08/27 08:54:44 [Info] [154526732] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > x509: certificate signed by unknown authority
```
Level Info/Debug are too verbose for users to find the **root cause of a failing configuration**. Show at warning level is more reasonable.

show vmess decode errors at warning level

---

transport/internet/sockopt_linux.go

Fix https://github.com/v2ray/v2ray-core/issues/1881

Add SO_REUSEPORT (kernel level load balance) support

---

app/dispatcher/default.go
common/log/access.go
common/mux/server.go
proxy/http/server.go
proxy/shadowsocks/server.go
proxy/socks/server.go
proxy/vmess/inbound/inbound.go

把v2fly那边的提交合过来了. https://github.com/v2fly/v2ray-core/pull/5
和那时候的相比, 把mux的打印也加上了
issue: #1639
效果
```
2019/06/06 14:55:52 tcp:127.0.0.1:4187 accepted tcp:www.google.com:443 [proxy]
2019/06/06 14:55:54 tcp:127.0.0.1:4190 accepted tcp:www.baidu.com:443 [direct]
```

access log add detour tag

---

transport/internet/tls/config_windows.go

Relates PR/Issues: 
https://github.com/v2ray/v2ray-core/issues/1513
https://github.com/shadowsocks/v2ray-plugin/pull/128
It should load the given certificate whether the `DisableSystemRoot` was set or not.
Furthermore, the Windows implementation is also not consistent with other platforms.

Fix self-signed certificates on Windows

---

proxy/vmess/inbound/inbound.go

fixed add new vmess user bug.
when add new vmess user, just add the key(u.email) to the map(v.cache), the value of map is nil.

fixed add new vmess user bug

---

app/dispatcher/default.go
common/log/access.go

判断了下 `handler.Tag()`. 
有可能是空的, 导致只打印了一个`[]`

check detour tag size

---

common/buf/reader.go

Revert changes introduced in 844f6937, fixes #1872 and #1974.
Holding one byte in advance would cause ReadFrom() blocks till timeout in case the remote server has just one byte to send, which is exactly how iperf3 server behaves.

fix ReadBuffer()

---

app/log/log.go
infra/conf/v2ray.go

Load logger module as early as possible, so that other modules could print their own logs during program initiating.
Here's example logs during the initial running.
```
V2Ray 4.21.4 (user) 20191115-171558
A unified platform for anti-censorship.
2019/11/19 14:10:09 [Debug] v2ray.com/core/app/log: Logger started
2019/11/19 14:10:09 [Info] v2ray.com/core/app/dns: DNS: classic server inited 1.1.1.1:53
2019/11/19 14:10:09 [Debug] v2ray.com/core/app/stats: create new counter inbound>>>proxy>>>traffic>>>uplink
2019/11/19 14:10:09 [Debug] v2ray.com/core/app/stats: create new counter inbound>>>proxy>>>traffic>>>downlink
2019/11/19 14:10:09 [Debug] v2ray.com/core/app/proxyman/inbound: creating stream worker on 0.0.0.0:10808
2019/11/19 14:10:09 [Debug] v2ray.com/core/app/stats: create new counter …
```

Earlylogger

---

common/buf/buffer.go
common/buf/reader.go
common/buf/readv_reader.go

Previously the ReadBuffer() uses in SingleReader and ReadVReader are both not correctly propagate read errors. Specifically, this PR fixes the case where the underlying io.Reader returns some data and io.EOF in the same time.

properly propagate Reader errors

---

common/platform/ctlcmd/ctlcmd.go
common/platform/platform.go
infra/conf/v2ray.go
infra/control/command.go
infra/control/config.go
main/main.go

A common way of reading multiple config file is to scan a directory and read config files inside by the order of their names. This PR make multiple config feature more practical by adding `-confdir` arg.
* v2ray arg: `-confdir` - A dir with multiple json config
* env `v2ray.location.confdir` or `V2RAY_LOCATION_CONFDIR` 
* more details logs about config during program start.
When use with multiple config, lines after `<v2ctl message>` will tell the order of how config file is processed.
```
$ ./v2ray -confdir ./vjson
V2Ray 4.22.0 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
2019/12/31 13:45:49 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message> 
v2ctl> Read config:  vjson/01dohipm.json
v2ctl> Read config:  vjson/02doh.json
v2ctl> …
```

add arg -confdir

---

release/install-release.sh

refactor: Clean up install-release.sh

---

.gitignore
app/dns/dohdns.go
app/dns/udpns.go

1. d520bc2 解决了在请求AAAA记录时，DoH服务器返回A记录的问题，相关issues #2211 
2. be9ce7f 将DNS查询按域名和A和AAAA进行分组订阅，避免了同时查询某域名的A和AAAA记录时，提前sub.Wait()结束，导致在for循环中反复调用s.findIPsForDomain，影响性能。
3. be9ce7f 解决DoH模式下某A/AAAA查询为空的时候在func QueryIP的for循环中无法正确return，反复循环影响性能，且在其后由于timeout而导致轮询DNS服务器，导致在该情况下的DNS请求迟迟无法结束。

DoH性能问题、DoH下AAAA重新过滤、DNS查询分组订阅

---

transport/internet/sockopt_freebsd.go
transport/internet/sockopt_other.go
transport/internet/tcp/sockopt_freebsd.go
transport/internet/tcp/sockopt_other.go
transport/internet/udp/hub_freebsd.go
transport/internet/udp/hub_other.go

transparent proxy (pf rdr) in IPv4 environment
support both tcp and udp
enable TCP_FASTOPEN, SO_REUSEPORT_LB, SO_REUSEADDR
sockopt:mark is mapped to SO_USER_COOKIE

add freebsd support

---

release/config/systemd/v2ray.service

做了一点微小的工作，例如：
去掉了在非 `forking` 类型中几乎无意义的 `PIDFile` （[因为 systemd 不会写入](https://www.freedesktop.org/software/systemd/man/systemd.service.html#PIDFile=)）
把[不推荐使用](https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/)的 `Wants=network.target` 换成 `Wants=network-online.target nss-lookup.target`

v2ray.service upgrade

---

app/reverse/bridge.go
proxy/http/client.go

In standard HTTP proxy, client will wait until proxy connects to the destination and send 200 OK back. This introduce 1 RTT overhead. If we send the content right after writing the CONNECT command, this could be eliminated.
As for compatibility, a standard http proxy should be able to separate the command and content by \r\n\r\n. In my test, most proxy server can handle this behavior.
With this optimization, HTTPS proxy can have the same overhead as other TLS based protocols.

Reduce http proxy client overhead by 1RTT

---

transport/internet/sockopt_linux.go
transport/internet/udp/hub_linux.go

should use IPV6_RECVORIGDSTADDR. now working as expected.
#1979 #2209 #2214 #2225

fix tproxy udp "unable to get destination" in IPv6 environment

---

transport/internet/sockopt_linux.go

It seems IPV6_RECVORIGDSTADDR & IP_RECVORIGDSTADDR must be set at the same time when dokodemo-door is listening on "0.0.0.0" so that both IPv4 & IPv6 can work properly.
@ToutyRater @changyp6

fix udp not work in ipv4 using common config

---

app/dispatcher/default.go
app/dns/dohdns.go
common/session/session.go

Optimize to DOH machanism:
1. DOH `https+local` mode: Uses `internet.effetiveSystemDialer`,  complies with API `RegisterDialerController`, allowing third-party applications (eg: android clients) work with DOH.
1. DOH `https` remote mode: Avoid resolving DOH hostnames locally as results may end up  contaminated. Also, skips routing rules, sending the doh request directly via the default outbound.

doh route strategy optimized

---

release/user-package.sh

修正当 releases 页存在多个 release 文件时（现在统统都是这样了），脚本错误将多个文件下载并合并为一个 dat 文件的问题。
该问题会导致 dat 文件无法被 v2ctl 程序解析。
// 另包含参考 shellcheck 程序给出的修改建议 SC2086，对脚本中变量的引用添加了必要的双引号。
在自己服务器上运行脚本构建了 Linux/Windows 两个平台的 release 文件，没有观察到破坏情况。

修复构建脚本的错误下载逻辑

---

main/main.go

In the previous commit, environment var `v2ray.location.confdir` effects only if neither `-config` or `-confdir` specified, it is unintended.
Now the `confdir` effects in the following order:
1. arg `-confdir
2. env `v2ray.location.confdir` or `V2RAY_LOCATION_CONFDIR`

fix confdir env startup priority

---

transport/internet/sockopt_freebsd.go

FreeBSD 11 is a Production Release, so add back required SO_REUSEPORT support.
Still use [SO_REUSEPORT_LB](https://reviews.freebsd.org/D11003) in FreeBSD 12+, which allow multiple programs or threads to bind to the same port and incoming connections will be load balanced using a hash function.

add SO_REUSEPORT for freebsd 11

---

infra/conf/v2ray.go
main/main.go

multi-config didn't consider depreciated configs.
But since we haven't retire the those depreciated attributes, the support should be continued.

fix config compatibility with old inbound/inboundDetors/out

---

release/install-release.sh

```
cat /etc/centos-release
CentOS Linux release 7.7.1908 (Core)
```
该系统既有systemd又有systemV，并且之前已经安装过了systemd的启动脚本。现在的逻辑就会走到systemV的安装流程，安装daemon时就会报错。

修复安装脚本添加自启动时报错的问题

---

release/config/systemd/v2ray.service
release/config/systemd/v2ray@.service

AmbientCapabilities= 换为 CapabilityBoundingSet= 可以缩小默认配置下使用 root 的权限
NoNewPrivileges=yes 可以保证进程不会取得新权限
CapabilityBoundingSet= 增加 CAP_NET_RAW 在普通用户下以获得透明代理的能力
在 a75525262fa60ab8a0c0ca05441b93ab16d43d2c 增加了 v2ray@.service

add NoNewPrivileges=yes & CAP_NET_RAW

---

release/install-release.sh

https://github.com/v2ray/v2ray-core/issues/2373

fix get the latest release tag error

---

app/proxyman/inbound/worker.go
common/buf/copy.go
proxy/dokodemo/dokodemo.go

修复一个导致 TPROXY 下 v2ray 断流的问题

---

common/buf/readv_posix.go
common/buf/readv_unix.go
transport/internet/domainsocket/listener.go
transport/internet/sockopt_other.go

Previously v2ray can not be built on illumos due to following reasons:
1. missing build tags in transport/internet/sockopt_other.go
2. many definitions in syscall does not exist on illumos
This commit addresses these problems by adding missing build tags, and
updates those missing syscall deps on illumos to use x/sys/unix.
Fix #2358.

Fix build failure on illumos

---

app/proxyman/inbound/worker.go
common/buf/copy.go
proxy/dokodemo/dokodemo.go

Reverts v2ray/v2ray-core#2348
由于缺少足够review和报告，临时在Release中移除该部分

Revert "修复一个导致 TPROXY 下 v2ray 断流的问题"

---

proxy/http/server.go

非抢先验证是指建立隧道时不会主动发送Proxy-Authorization，在之后收到407响应后才会再带上这个验证。
服务端目前在代理验证不通过时现在将直接关闭连接，而客户端在不知情的情况下仍会在这个连接中发送请求，导致客户端报错。
因此应在关闭连接时明确返回close。
受此影响的客户端：okhttp3 <= 3.11.0

支持非抢先验证的客户端

---

main/main.go

os.Kill is non-catchable, non-ignorable

Some code optimization
